---
swagger: "2.0"
info:
  title: "Weather History by Station ID"
  version: "v1.0"
  description: "An API for getting historical weather data. The data source is the\
    \ NOAA CHCN dataset. The GHCN-Daily is an integrated database of daily climate\
    \ summaries from land surface stations across the globe, and is comprised of daily\
    \ climate records from over 100,000 stations in 180 countries and territories,\
    \ and includes some data from every year since 1763."
host: ""
schemes:
- "https"
basePath: "/"
paths:
  /v1/weather-history/stations:
    get:
      summary: "Find the IDs for weather stations located near a street address, landmark,\
        \ or common name for a place."
      description: ""
      operationId: "stations"
      parameters:
      - type: "string"
        name: "near"
        required: true
        default: ""
        in: "query"
        description: "A street address, landmark, or common name for a place"
      - type: "string"
        name: "apikey"
        required: true
        in: "query"
        description: "Your API key"
        default: ""
      responses:
        "200":
          description: "Object with list of matching stations near the place that\
            \ matches the search"
          schema:
            type: "object"
            properties:
              address:
                type: "string"
                description: "The address or place that was used in the search."
              lat:
                type: "number"
                description: "The latitude of the matched place."
                example: 39.8560963
              lon:
                type: "number"
                description: "The longitude of the matched place."
                example: -104.6737376
              stations:
                type: "array"
                items:
                  properties:
                    id:
                      type: "string"
                      example: "US1CODN0073"
                    name:
                      type: "string"
                      example: "DIA 1.0 NE"
                    state:
                      type: "string"
                      example: "CO"
                    lat:
                      type: "number"
                      example: 39.8665
                    lon:
                      type: "number"
                      example: -104.6508
                    hcn_crn_flag:
                      type: "string"
                      example: "HCN"
                    distance:
                      type: "number"
                      example: 1.61
        "401":
          description: "Unauthorized"
        "429":
          description: "Quota violation, rate violation"
        "500":
          description: "Server error"
        default:
          description: "a list of weather stations near the address"
  /v1/weather-history/stations/{station_id}/years/{year}/temp:
    get:
      summary: "Get temperture data for a given station for a given year"
      description: "Returns 365 days of high and low temperatures for a weather station.\
        \ Use the .../stations API to find a weather station"
      operationId: "temp"
      parameters:
      - type: "string"
        default: "your-api-key"
        name: "apikey"
        required: true
        in: "query"
        description: "Your API key"
      - name: "year"
        in: "path"
        description: "year"
        required: true
        type: "string"
        default: "2015"
      - name: "station_id"
        in: "path"
        description: "Weather station id, use .../stations to find it"
        required: true
        type: "string"
        default: "USW00023169"
      responses:
        "200":
          description: "Successful response"
        "401":
          description: "Unauthorized"
        "429":
          description: "Quota violation, rate violation"
        "500":
          description: "Server error"
  /v1/weather-history/stations/{station_id}/years/{year}/wind:
    get:
      summary: "BigQuery - Get wind data for a given station for a given year"
      description: ""
      operationId: "wind"
      parameters:
      - type: "string"
        default: "your-api-key"
        name: "apikey"
        required: true
        in: "query"
        description: "Your API key"
      - name: "year"
        in: "path"
        description: "year"
        required: true
        type: "string"
        default: "2015"
      - name: "station_id"
        in: "path"
        description: "Weather station id, use .../stations to find it"
        required: true
        type: "string"
        default: "USW00023169"
      responses:
        "200":
          description: "Successful response"
        "401":
          description: "Unauthorized"
        "429":
          description: "Quota violation, rate violation"
        "500":
          description: "Server error"
